version: "3.4"

networks:
  opnet:
    ipam:
      driver: default
      config:
        - subnet: 10.0.11.0/24

services:

  op-geth:
    networks:
      - opnet
    image: 294354037686.dkr.ecr.ap-northeast-1.amazonaws.com/blockchain-op-geth:36e4a277
    restart: unless-stopped
    stop_grace_period: 1m
    env_file:
      - .env
    volumes:
      - ./scripts/:/scripts
      - ./assets/:/assets
      - ${OP_GETH_DATADIR:-/dbk/op-geth}:/op-geth
      - ${OP_NODE_DATADIR:-/dbk/op-node}:/op-node
    ports:
      - ${PORT__OP_GETH_HTTP:-8545}:8545
      - ${PORT__OP_GETH_METRIC_PORT:-6060}:6060
    command:
      - --datadir=/op-geth
      - --http
      - --http.corsdomain=*
      - --http.vhosts=*
      - --http.addr=0.0.0.0
      - --http.api=miner,web3,debug,eth,txpool,net,engine,admin
      - --syncmode=full
      - --gcmode=archive
      - --nodiscover
      - --maxpeers=0
      - --authrpc.vhosts=*
      - --authrpc.addr=0.0.0.0
      - --authrpc.port=8551
      - --authrpc.jwtsecret=/op-geth/jwt.txt
      - --rollup.disabletxpoolgossip=true
      - --password=/op-geth/password
      - --allow-insecure-unlock
      - --mine
      - --miner.etherbase=$SEQUENCER_ADDR
      - --txpool.pricelimit=500000000000
      - --txpool.nolocals
      - --unlock=$SEQUENCER_ADDR
        #- --pprof --pprof.addr=0.0.0.0 --pprof.port 6060

  op-node:
    networks:
      - opnet
    image: 294354037686.dkr.ecr.ap-northeast-1.amazonaws.com/blockchain-dbk:op-node-5990c89c
    restart: unless-stopped
    stop_grace_period: 1m
    env_file:
      - .env
    volumes:
      - ./scripts/:/scripts
      - ./assets/:/assets
      - ${OP_GETH_DATADIR:-/dbk/op-geth}:/op-geth
      - ${OP_NODE_DATADIR:-/dbk/op-node}:/op-node
    ports:
      - ${PORT__OP_NODE_HTTP:-8547}:8547
      - ${PORT__OP_NODE_P2P:-9222}:9222
      - ${PORT__OP_NODE_METRIC_PORT:-7300}:7300
    command:
      - op-node
        #- --l1=http://dbk.trace.geth.blockchain
        #- --l1=https://rpc.ankr.com/eth_goerli
      - --l1=https://goerli.blockpi.network/v1/rpc/public
      - --l1.trustrpc=true
      - --l2=http://op-geth:8551
      - --l2.jwt-secret=/op-geth/jwt.txt
      - --sequencer.enabled
      - --sequencer.l1-confs=3
      - --verifier.l1-confs=3
      - --rollup.config=/assets/rollup.json
      - --rpc.addr=0.0.0.0
      - --rpc.port=8547
      - --rpc.enable-admin
      - --metrics.enabled
      - --p2p.sequencer.key=$SEQUENCER_KEY
      - --p2p.advertise.ip=$P2P_ADVERTISE_IP
      - --p2p.sync.req-resp
      - --p2p.priv.path=/op-node/opnode_p2p_priv.txt